#!/bin/bash

# Runs the unit tests with nodeunit

cd "$(dirname "$0")" || {
	echo "ERROR: failed to switch to the correct directory"
	exit 1
}

if [[ $(type -t nodeunit) != file ]]; then
	echo "ERROR: nodeunit doesn't seem to be installed."
	echo "The suggested method for installing it is:"
	echo "    curl http://npmjs.org/install.sh | sudo sh"
	echo "    sudo npm install nodeunit"
	exit 1
fi

cleanup() {
	for pid in "${pids[@]}"; do
		kill $pid
	done
	rm -rf helpers/cache
	rm -f helpers/access_log
}
pids=()
trap cleanup INT TERM EXIT

rm -rf helpers/cache; mkdir helpers/cache
rm -rf helpers/yumcache; mkdir helpers/yumcache
rm -f helpers/access_log

# start a background proxy and webserver
node helpers/webserver.js & pids+=($!)
node helpers/proxy.js & pids+=($!)
node helpers/yumproxy.js & pids+=($!)

# hacky sleep to let servers start up before running tests
sleep .1

nodeunit .

# vim: noet
