#!/bin/bash -e

cd "$(dirname "$0")"

# install node
add-apt-repository ppa:chris-lea/node.js
apt-get update
apt-get install -y python-software-properties nodejs npm


cd /repoproxy
npm update
#( node proxy.js & )
